-- TeamDeck canonical schema. Run in Supabase SQL editor or via supabase db push.
create extension if not exists pgcrypto;
create type public.task_status as enum ('todo','in_progress','review','done');
create type public.member_role as enum ('owner','member');

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, email text, avatar_url text, last_seen_at timestamptz default now(), created_at timestamptz default now());
create table if not exists public.projects (id uuid primary key default gen_random_uuid(), name text not null, description text default '', color text default '#C8F169', created_by uuid not null references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.project_members (project_id uuid references public.projects(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, role public.member_role not null default 'member', created_at timestamptz default now(), primary key(project_id,user_id));
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, description text default '', status public.task_status not null default 'todo', priority smallint not null default 2 check(priority between 1 and 3), assignee_id uuid references public.profiles(id) on delete set null, due_date date not null, position double precision not null default 1, version integer not null default 1, created_by uuid not null references public.profiles(id), updated_by uuid not null references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.task_dependencies (task_id uuid references public.tasks(id) on delete cascade, depends_on_id uuid references public.tasks(id) on delete cascade, created_at timestamptz default now(), primary key(task_id,depends_on_id), check(task_id <> depends_on_id));
create table if not exists public.comments (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade, author_id uuid not null references public.profiles(id), body text not null, created_at timestamptz default now(), linked_task_id uuid references public.tasks(id) on delete set null);
create table if not exists public.attachments (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade, uploader_id uuid not null references public.profiles(id), storage_path text not null, file_name text not null, mime_type text, size_bytes bigint, created_at timestamptz default now());
create table if not exists public.activity_log (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, task_id uuid references public.tasks(id) on delete cascade, actor_id uuid not null references public.profiles(id), action text not null, meta jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, task_id uuid references public.tasks(id) on delete cascade, comment_id uuid references public.comments(id) on delete cascade, kind text not null, read boolean not null default false, created_at timestamptz default now());

create index if not exists tasks_project_idx on public.tasks(project_id); create index if not exists tasks_assignee_idx on public.tasks(assignee_id); create index if not exists tasks_due_idx on public.tasks(due_date); create index if not exists activity_project_time_idx on public.activity_log(project_id,created_at desc); create index if not exists notifications_user_read_idx on public.notifications(user_id,read);

create or replace function public.is_project_member(pid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.project_members pm where pm.project_id = pid and pm.user_id = auth.uid()); $$;
create or replace function public.update_task(p_id uuid, p_expected_version integer, p_patch jsonb) returns public.tasks language plpgsql security invoker set search_path = public as $$ declare updated public.tasks; begin update public.tasks set title=coalesce(p_patch->>'title',title), description=coalesce(p_patch->>'description',description), status=coalesce((p_patch->>'status')::public.task_status,status), priority=coalesce((p_patch->>'priority')::smallint,priority), assignee_id=case when p_patch ? 'assignee_id' then nullif(p_patch->>'assignee_id','')::uuid else assignee_id end, due_date=coalesce((p_patch->>'due_date')::date,due_date), version=version+1, updated_by=auth.uid(), updated_at=now() where id=p_id and version=p_expected_version returning * into updated; if not found then raise exception 'VERSION_CONFLICT' using errcode='40001'; end if; return updated; end; $$;

alter table public.profiles enable row level security; alter table public.projects enable row level security; alter table public.project_members enable row level security; alter table public.tasks enable row level security; alter table public.task_dependencies enable row level security; alter table public.comments enable row level security; alter table public.attachments enable row level security; alter table public.activity_log enable row level security; alter table public.notifications enable row level security;
create policy if not exists profiles_self_or_project on public.profiles for select using (id=auth.uid() or exists(select 1 from public.project_members pm join public.tasks t on t.project_id=pm.project_id where pm.user_id=auth.uid() and t.assignee_id=profiles.id));
create policy if not exists projects_member_read on public.projects for select using (public.is_project_member(id)); create policy if not exists projects_member_write on public.projects for insert with check (auth.uid()=created_by); create policy if not exists projects_member_update on public.projects for update using (public.is_project_member(id)); create policy if not exists projects_owner_delete on public.projects for delete using (exists(select 1 from public.project_members pm where pm.project_id=id and pm.user_id=auth.uid() and pm.role='owner'));
create policy if not exists project_members_read on public.project_members for select using (public.is_project_member(project_id)); create policy if not exists project_members_write on public.project_members for insert with check(public.is_project_member(project_id));
create policy if not exists tasks_member_all on public.tasks for all using(public.is_project_member(project_id)) with check(public.is_project_member(project_id)); create policy if not exists deps_member_all on public.task_dependencies for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))); create policy if not exists comments_member_all on public.comments for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))); create policy if not exists attachments_member_all on public.attachments for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))); create policy if not exists activity_member_read on public.activity_log for select using(public.is_project_member(project_id)); create policy if not exists notifications_self on public.notifications for all using(user_id=auth.uid()) with check(user_id=auth.uid());

insert into storage.buckets(id,name,public) values ('task-files','task-files',false) on conflict do nothing;
alter publication supabase_realtime add table public.tasks; alter publication supabase_realtime add table public.comments; alter publication supabase_realtime add table public.attachments; alter publication supabase_realtime add table public.notifications;
